# Generated by Django 4.1.2 on 2023-01-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Out For Shipping', 'Out For Shipping'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Refunded', 'Refunded')], default='Confirmed', max_length=150),
        ),
    ]
